name: Bump version name
on:
  push:
    branches:
      - bug/action-permissions
  pull_request:
    # branches:
    #   - develop
    #   - main
    types: [opened]
jobs:
  bump-version-name:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read  
    if: "contains(github.head_ref, 'release/')"
    steps:
    - uses: actions/checkout@v2
    - name: Bump script
      env:
        HEAD_REF: ${{ github.head_ref }}
      run: |
        ./scripts/bump-version.sh "$HEAD_REF"
        git diff
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add bitrise.yml
        git add package.json
        git commit -m "Bump version name"
        git push origin HEAD:"$HEAD_REF" --force
